Manhattan\Bundle\ConsoleBundle\Entity\User:
    type:  entity
    table: console_user

    repositoryClass: Manhattan\Bundle\ConsoleBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            type: string
            length: 255
            column: first_name
            nullable: true
        lastName:
            type: string
            length: 255
            column: last_name
            nullable: true
        created_at:
            type: datetime
        updated_at:
            type: datetime

    oneToMany:
        socialAccounts:
            targetEntity: Manhattan\Bundle\ConsoleBundle\Entity\User\SocialAccount
            mappedBy: user
            orphanRemoval: true
            cascade: [ persist, remove ]

    lifecycleCallbacks:
        prePersist: [ onCreate ]
        preUpdate:  [ onUpdate ]
