Manhattan\Bundle\ConsoleBundle\Entity\User\SocialAccount:
    type:  entity
    table: console_user_social

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        outlet:
            type: string
            length: 40
            column: outlet
        identifier:
            type: string
            length: 255
            column: identifier

    manyToOne:
        user:
            targetEntity: Manhattan\Bundle\ConsoleBundle\Entity\User
            inversedBy:   socialAccounts
            joinColumn:
                name: user_id
                referencedColumnName: id
            cascade:
                - persist
                - merge
