# FOS UserBundle
fos_user:
    db_driver:      orm
    firewall_name:  secured_area

    service:
        mailer:     fos_user.mailer.twig_swift

# Set Defaults for the Bundle's Configuration
manhattan_console:
    user_roles:
        - { role: ROLE_ADMIN, name: User }
        - { role: ROLE_SUPER_ADMIN, name: Administrator }

# MOPA Bootstrap
mopa_bootstrap:
    menu: ~
