# FOS UserBundle
fos_user:
    db_driver:      orm
    firewall_name:  secured_area

    service:
        mailer:     fos_user.mailer.twig_swift

# Set Defaults for the Bundle's Configuration
manhattan_console:
    user_roles:
        - { role: ROLE_ADMIN, name: User }
        - { role: ROLE_SUPER_ADMIN, name: Administrator }

# MOPA Bootstrap
mopa_bootstrap:
    menu: ~
    form:
        render_fieldset: false # default is true
        render_collection_item: true # default is true
        show_legend: false # default is true
        horizontal_label_class:  col-sm-3 control-label
        collection:
            widget_remove_btn:
                attr:
                    class:            btn btn-danger
                label:                Remove
                icon:                 trash
                icon_inverted:        true
            widget_add_btn:
                attr:
                    class:            btn btn-info
                label:                Add
                icon:                 plus-sign
                icon_inverted:        true
