# Bootstrap Bundle
mopa_bootstrap:
    navbar: ~
    form: ~

parameters:
    manhattan.console.navbar.generic: Mopa\Bundle\BootstrapBundle\Navbar\GenericNavbar

services:
    manhattan.console.menu_builder:
        class: Manhattan\Bundle\ConsoleBundle\Navbar\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher", "@security.context"]

    manhattan.console.menu:
        class: Knp\Menu\MenuItem
        factory_service: manhattan.console.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainmenu }

    manhattan.console.rightmenu:
        class: Knp\Menu\MenuItem
        factory_service: manhattan.console.menu_builder
        factory_method: createRightSideMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: rightmenu }

# JMS Security
jms_security_extra:
    secure_all_services: true

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ConsoleBundle]
        directories: ["%kernel.root_dir%/../src"]

# FOS UserBundle
fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: Manhattan\Bundle\ConsoleBundle\Entity\User
