_security:
    resource: "@ManhattanConsoleBundle/Controller/SecurityController.php"
    type:     annotation

_console:
    resource: "@ManhattanConsoleBundle/Controller/ConsoleController.php"
    type:     annotation