security:
    encoders:
        Manhattan\Bundle\ConsoleBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls: 
        main:
            pattern:    ^/console/
            form_login:
                check_path: /console/login_check
                login_path: /console/login
                provider: fos_userbundle
            logout:
                path:   /console/logout
                target: /console/

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
