security:
    encoders:
        Manhattan\Bundle\ConsoleBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        test_console:
            memory:
                users:
                    admin: { password: test, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/console(.*)
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     /console/login
                check_path:     /console/login_check
            logout:
                path:           /console/logout
                target:         /console
            anonymous:    ~

    access_control:
        - { path: ^/console/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console/register, role: ROLE_ADMIN }
        - { path: ^/console/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console/admin/, role: ROLE_ADMIN }
