security:
    encoders:
        Manhattan\Bundle\ConsoleBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
           pattern:  ^/console/login$
           security: false

        secured_area:
            pattern:    ^/console/
            form_login:
                check_path: /console/login_check
                login_path: /console/login
                provider: fos_userbundle
            logout:
                path:   /console/logout
                target: /console/

    access_control:
        - { path: ^login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/console/admin/, role: ROLE_ADMIN }
