security:
    encoders:
        Manhattan\Bundle\ConsoleBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        test_console:
            memory:
                users:
                    admin: { password: test, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            request_matcher:    manhattan.console.subdomain_request_matcher
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     /login
                check_path:     /login_check
            logout:
                path:           /logout
                target:         /
            anonymous:    ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, host: console.%domain% }
        - { path: ^/register, role: ROLE_SUPER_ADMIN, host: console.%domain% }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, host: console.%domain% }
        - { path: ^/admin, role: ROLE_ADMIN, host: console.%domain% }
